# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_pb2 as grpc__pb2


class BJLStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handle = channel.unary_unary(
                '/Arithmetic.BJL/Handle',
                request_serializer=grpc__pb2.Request.SerializeToString,
                response_deserializer=grpc__pb2.Reply.FromString,
                )
        self.NewPoker = channel.unary_unary(
                '/Arithmetic.BJL/NewPoker',
                request_serializer=grpc__pb2.Empty.SerializeToString,
                response_deserializer=grpc__pb2.Poker.FromString,
                )


class BJLServicer(object):
    """The greeting service definition.
    """

    def Handle(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewPoker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BJLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handle': grpc.unary_unary_rpc_method_handler(
                    servicer.Handle,
                    request_deserializer=grpc__pb2.Request.FromString,
                    response_serializer=grpc__pb2.Reply.SerializeToString,
            ),
            'NewPoker': grpc.unary_unary_rpc_method_handler(
                    servicer.NewPoker,
                    request_deserializer=grpc__pb2.Empty.FromString,
                    response_serializer=grpc__pb2.Poker.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Arithmetic.BJL', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BJL(object):
    """The greeting service definition.
    """

    @staticmethod
    def Handle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Arithmetic.BJL/Handle',
            grpc__pb2.Request.SerializeToString,
            grpc__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewPoker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Arithmetic.BJL/NewPoker',
            grpc__pb2.Empty.SerializeToString,
            grpc__pb2.Poker.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
